name: "samtools_sort"
description: Sort BAM/SAM/CRAM file
keywords:
  - sort
  - bam
  - sam
  - cram
  - samtools
tools:
  - samtools:
      description: Tools for dealing with SAM, BAM and CRAM files
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: BAM/SAM/CRAM file
      pattern: "*.{bam,sam,cram}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.sorted.bam"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@wasp2-team"
maintainers:
  - "@wasp2-team"
