name: "bwa_mem"
description: Align reads to reference using BWA MEM algorithm
keywords:
  - align
  - alignment
  - bwa
  - mem
  - fastq
  - bam
tools:
  - bwa:
      description: BWA is a software package for mapping low-divergent sequences against a large reference genome
      homepage: https://github.com/lh3/bwa
      documentation: https://github.com/lh3/bwa#type
      doi: 10.1093/bioinformatics/btp324
      licence: ["GPL-3.0-or-later"]
  - samtools:
      description: Tools for dealing with SAM, BAM and CRAM files
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - reads:
      type: file
      description: FASTQ file(s) (single or paired-end)
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - index:
      type: directory
      description: BWA index directory
      pattern: "bwa/"
  - fasta:
      type: file
      description: Reference FASTA file
      pattern: "*.{fa,fasta}"
  - sort_bam:
      type: boolean
      description: If true, output sorted BAM; if false, output unsorted BAM
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: Output BAM file
      pattern: "*.bam"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@wasp2-team"
maintainers:
  - "@wasp2-team"
