# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install -e .[docs]

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
