# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_markduplicates_picard"
description: Mark duplicates with Picard and collect BAM statistics
keywords:
  - bam
  - duplicates
  - picard
  - dedup
  - qc
components:
  - picard/markduplicates
  - bam_stats_samtools
input:
  - ch_bam:
      type: channel
      description: |
        Channel containing BAM files to deduplicate
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - ch_fasta:
      type: channel
      description: |
        Channel containing reference FASTA
        Structure: path(fasta)
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
  - ch_fai:
      type: channel
      description: |
        Channel containing FASTA index
        Structure: path(fasta.fai)
      pattern: "*.fai"
output:
  - bam:
      type: channel
      description: |
        Deduplicated BAM file
        Structure: [ val(meta), path(bam) ]
      pattern: "*.markdup.bam"
  - bai:
      type: channel
      description: |
        BAM index file
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - metrics:
      type: channel
      description: |
        Picard MarkDuplicates metrics
        Structure: [ val(meta), path(metrics) ]
      pattern: "*.metrics.txt"
  - stats:
      type: channel
      description: |
        Samtools stats output
        Structure: [ val(meta), path(stats) ]
      pattern: "*.stats"
  - flagstat:
      type: channel
      description: |
        Samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
      pattern: "*.flagstat"
  - idxstats:
      type: channel
      description: |
        Samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
      pattern: "*.idxstats"
  - versions:
      type: channel
      description: |
        Version information
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@jjaureguy760"
maintainers:
  - "@jjaureguy760"
