# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "mae_detect"
description: Detect mono-allelic expression using binomial test on allele-specific counts
keywords:
  - mono-allelic
  - allele-specific
  - binomial-test
  - expression-imbalance

tools:
  - scipy:
      description: Scientific computing library for Python
      homepage: https://scipy.org/
      documentation: https://docs.scipy.org/doc/scipy/
      licence: ["BSD-3-Clause"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample1' ]
    - counts:
        type: file
        description: TSV file with allele counts (ref_count, alt_count columns)
        pattern: "*.tsv"
  - - min_count:
        type: integer
        description: Minimum total count threshold for testing
  - - padj_cutoff:
        type: float
        description: Adjusted p-value cutoff for significance
  - - alt_ratio_threshold:
        type: float
        description: Allelic ratio threshold for MAE classification

output:
  - mae_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1' ]
      - "*.mae_results.tsv":
          type: file
          description: TSV file with mono-allelic expression detection results
          pattern: "*.mae_results.tsv"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@Jaureguy760"
maintainers:
  - "@Jaureguy760"
