# nf-core pipeline configuration
# See: https://nf-co.re/docs/nf-core-tools/pipelines/lint

repository_type: pipeline

# nf-core template version this pipeline is based on
template:
  skip:
    - .github/
    - .gitignore
    - CODE_OF_CONDUCT.md
    - LICENSE
    - assets/email_template.html
    - lib/

# Linting configuration
lint:
  # Skip checks that don't apply to this pipeline
  files_exist:
    - docs/README.md
    - docs/output.md
    - docs/usage.md
    - .github/workflows/
    - .github/ISSUE_TEMPLATE/
    - .github/PULL_REQUEST_TEMPLATE.md
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - LICENSE
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.homePage
    - manifest.doi
  schema_lint: false
  modules_structure: false
  # Skip module-specific lints for local WASP2 modules
  modules:
    - wasp2_count_variants
    - wasp2_filter_remapped
    - wasp2_find_imbalance
    - wasp2_make_reads
  subworkflows:
    - prepare_genome
    - wasp_mapping

# nf-core modules configuration
nf_core_modules:
  https://github.com/nf-core/modules.git:
    update: true
