# nf-core pipeline configuration
repository_type: pipeline

# Linting configuration - skip checks that don't apply to custom pipelines
lint:
  files_exist:
    - docs/README.md
    - docs/output.md
    - docs/usage.md
    - .github/workflows/
    - .github/ISSUE_TEMPLATE/
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.html
    - assets/nf-core-PIPELINE_logo_light.png
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
    - lib/WorkflowMain.groovy
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - LICENSE
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.homePage
    - manifest.doi
    - params.validationSchemaIgnoreParams
  schema_lint: false
  modules_structure: false
  modules_config: false
  modules_json: false
