# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "wasp2_filter_remapped"
description: Filter remapped reads to remove mapping bias using WASP2 algorithm
keywords:
  - wasp
  - mapping-bias
  - allele-specific
  - filtering
  - remapping

tools:
  - wasp2:
      description: "WASP2: Allele-specific software for robust molecular QTL discovery"
      homepage: "https://github.com/mcvicker-lab/WASP2"
      documentation: "https://github.com/mcvicker-lab/WASP2/wiki"
      doi: "10.1038/nmeth.3582"
      licence: ["Apache-2.0"]
      identifier: biotools:wasp
  - samtools:
      description: "Tools for manipulating next-generation sequencing data"
      homepage: "http://www.htslib.org/"
      documentation: "http://www.htslib.org/doc/samtools.html"
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
      identifier: biotools:samtools

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample1', single_end:false ]
    - remapped_bam:
        type: file
        description: BAM file containing remapped reads with swapped alleles
        pattern: "*.bam"
    - remapped_bai:
        type: file
        description: Index for remapped BAM file
        pattern: "*.bam.bai"
    - to_remap_bam:
        type: file
        description: Intermediate BAM with reads that were sent for remapping
        pattern: "*_to_remap.bam"
    - keep_bam:
        type: file
        description: Intermediate BAM with reads that don't overlap variants
        pattern: "*_keep.bam"
    - wasp_json:
        type: file
        description: JSON file with WASP2 intermediate file paths
        pattern: "*_wasp_data_files.json"

output:
  - bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_wasp_filt.bam":
          type: file
          description: WASP-filtered BAM with mapping bias corrected reads
          pattern: "*_wasp_filt.bam"
      - "*_wasp_filt.bam.bai":
          type: file
          description: Index for filtered BAM
          pattern: "*_wasp_filt.bam.bai"
  - stats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_wasp_stats.txt":
          type: file
          description: Samtools flagstat statistics for the WASP-filtered BAM
          pattern: "*_wasp_stats.txt"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@Jaureguy760"
maintainers:
  - "@Jaureguy760"
