name: "wasp2_analyze"
description: Detect allelic imbalance using beta-binomial statistical modeling
keywords:
  - allelic-imbalance
  - beta-binomial
  - statistical-analysis
  - rna-seq
  - atac-seq
  - wasp

tools:
  - wasp2:
      description: |
        WASP2 is a tool for allele-specific analysis of next-generation sequencing data.
        The analyze module performs beta-binomial statistical modeling to detect
        significant allelic imbalance from allele count data.
      homepage: https://github.com/mcvickerlab/WASP2
      documentation: https://mcvickerlab.github.io/WASP2/
      tool_dev_url: https://github.com/mcvickerlab/WASP2
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information.
        e.g. `[ id:'sample1', phased:true ]`
        Optional `phased` key indicates if genotypes are phased.
  - counts:
      type: file
      description: |
        TSV file with allele counts from WASP2_COUNT.
        Must contain columns: chrom, pos, ref, alt, ref_count, alt_count
      pattern: "*.counts.tsv"

output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - stats:
      type: file
      description: |
        TSV file with allelic imbalance statistics.
        Columns: region, ref_count, alt_count, ratio, log2fc, pval, fdr_pval, dispersion
      pattern: "*.stats.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@Jaureguy760"
maintainers:
  - "@Jaureguy760"
