# Configuration file for the Sphinx documentation builder.
# WASP2 Documentation

import os
import sys

sys.path.insert(0, os.path.abspath("../../src"))

# Mock imports for modules that require compiled extensions
autodoc_mock_imports = [
    "wasp2_rust",
    "pysam",
    "pybedtools",
    "anndata",
    "scanpy",
]

# -- Project information -----------------------------------------------------
project = "WASP2"
copyright = "2025, Aaron Ho, Jeff Jaureguy, McVicker Lab"
author = "Aaron Ho, Jeff Jaureguy, McVicker Lab"

# The short X.Y version
version = "1.2"
# The full version, including alpha/beta/rc tags
release = "1.2.0"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    "sphinx.ext.autodoc",  # Auto-generate from docstrings
    "sphinx.ext.napoleon",  # Google/NumPy docstring support
    "sphinx.ext.viewcode",  # Add source code links
    "sphinx.ext.intersphinx",  # Link to other docs
    "sphinx_autodoc_typehints",  # Use our type hints!
    "sphinx.ext.autosummary",  # Generate summary tables
    "sphinx.ext.coverage",  # Coverage checker
    "sphinx.ext.todo",  # Support TODO items
]

# Add any paths that contain templates here, relative to this directory
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = []

# The suffix(es) of source filenames
source_suffix = ".rst"

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    "navigation_depth": 4,
    "show_nav_level": 2,
    "show_toc_level": 2,
    "navbar_align": "left",
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/Jaureguy760/WASP2-final",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "PyPI",
            "url": "https://test.pypi.org/project/wasp2-rust/",
            "icon": "fa-solid fa-box",
        },
    ],
    "use_edit_page_button": True,
    "announcement": "WASP2 v1.2.0 with Rust acceleration is now available!",
}

html_context = {
    "github_user": "Jaureguy760",
    "github_repo": "WASP2-final",
    "github_version": "main",
    "doc_path": "docs/source",
}

# Logo configuration
html_logo = "_static/logo.png"
html_favicon = "_static/logo.png"

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names
html_sidebars = {}

# -- Extension configuration -------------------------------------------------

# -- Options for autodoc extension -------------------------------------------

# This value controls how to represent typehints
autodoc_typehints = "description"  # Show types in parameter descriptions
autodoc_typehints_description_target = "documented"

# This value selects what content will be inserted into the main body
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# Automatically extract typehints when specified
autodoc_typehints_format = "short"

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

# -- Options for napoleon extension ------------------------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True
