name: "bwa_index"
description: Create BWA index from reference FASTA
keywords:
  - index
  - fasta
  - bwa
  - alignment
tools:
  - bwa:
      description: BWA is a software package for mapping low-divergent sequences against a large reference genome
      homepage: https://github.com/lh3/bwa
      documentation: https://github.com/lh3/bwa#type
      doi: 10.1093/bioinformatics/btp324
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. `[ id:'reference' ]`
  - fasta:
      type: file
      description: Reference FASTA file
      pattern: "*.{fa,fasta,fna}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. `[ id:'reference' ]`
  - index:
      type: directory
      description: BWA index directory containing index files
      pattern: "bwa/"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@wasp2-team"
maintainers:
  - "@wasp2-team"
