# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fastq_align_bwa"
description: Align reads with BWA-MEM and collect BAM statistics
keywords:
  - alignment
  - bwa
  - bam
  - map
  - fastq
components:
  - bwa/mem
  - samtools/index
  - bam_stats_samtools
input:
  - ch_reads:
      type: channel
      description: |
        Channel containing FASTQ reads
        Structure: [ val(meta), path(reads) ]
      pattern: "*.{fq,fastq,fq.gz,fastq.gz}"
  - ch_index:
      type: channel
      description: |
        Channel containing BWA index files
        Structure: path(index)
      pattern: "*.{amb,ann,bwt,pac,sa}"
  - ch_fasta:
      type: channel
      description: |
        Channel containing reference FASTA
        Structure: path(fasta)
      pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
output:
  - bam:
      type: channel
      description: |
        Aligned BAM file
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: channel
      description: |
        BAM index file
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - stats:
      type: channel
      description: |
        Samtools stats output
        Structure: [ val(meta), path(stats) ]
      pattern: "*.stats"
  - flagstat:
      type: channel
      description: |
        Samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
      pattern: "*.flagstat"
  - idxstats:
      type: channel
      description: |
        Samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
      pattern: "*.idxstats"
  - versions:
      type: channel
      description: |
        Version information
        Structure: path(versions.yml)
      pattern: "versions.yml"
authors:
  - "@jjaureguy760"
maintainers:
  - "@jjaureguy760"
