name: "bam_stats_samtools"
description: Generate BAM statistics using samtools stats, flagstat, and idxstats
keywords:
  - stats
  - flagstat
  - idxstats
  - bam
  - samtools
  - qc
components:
  - samtools/stats
  - samtools/flagstat
  - samtools/idxstats
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: Sorted and indexed BAM file
      pattern: "*.bam"
  - bai:
      type: file
      description: BAM index file
      pattern: "*.bam.bai"
  - fasta:
      type: file
      description: Reference FASTA file (optional, for CRAM)
      pattern: "*.{fa,fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - stats:
      type: file
      description: Samtools stats output with alignment metrics
      pattern: "*.stats"
  - flagstat:
      type: file
      description: Samtools flagstat output with flag statistics
      pattern: "*.flagstat"
  - idxstats:
      type: file
      description: Samtools idxstats output with per-chromosome counts
      pattern: "*.idxstats"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@wasp2-team"
maintainers:
  - "@wasp2-team"
