name: "fastq_align_bwa"
description: Align FASTQ reads to reference using BWA MEM, sort, index, and generate statistics
keywords:
  - align
  - alignment
  - bwa
  - fastq
  - bam
  - samtools
  - stats
components:
  - bwa/index
  - bwa/mem
  - bam_sort_stats_samtools
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - reads:
      type: file
      description: FASTQ file(s) for alignment
      pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - index:
      type: directory
      description: Pre-built BWA index (required)
      pattern: "bwa/"
  - fasta:
      type: file
      description: Reference FASTA file
      pattern: "*.{fa,fasta}"
  - sort_bam:
      type: boolean
      description: Whether to sort the output BAM file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.sorted.bam"
  - bai:
      type: file
      description: BAM index file
      pattern: "*.sorted.bam.bai"
  - csi:
      type: file
      description: CSI index file (for large chromosomes)
      pattern: "*.sorted.bam.csi"
  - stats:
      type: file
      description: Samtools stats output
      pattern: "*.stats"
  - flagstat:
      type: file
      description: Samtools flagstat output
      pattern: "*.flagstat"
  - idxstats:
      type: file
      description: Samtools idxstats output
      pattern: "*.idxstats"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@wasp2-team"
maintainers:
  - "@wasp2-team"
