# Bioconda Recipe for WASP2
# Submit to: https://github.com/bioconda/bioconda-recipes
#
# Instructions:
# 1. Fork bioconda-recipes
# 2. Copy this file to recipes/wasp2/meta.yaml
# 3. Update sha256 with actual PyPI sdist hash
# 4. Submit PR
#
# Reference: https://bioconda.github.io/contributor/workflow.html

{% set name = "wasp2" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # Get sha256 from: pip hash wasp2-{{ version }}.tar.gz
  sha256: "REPLACE_WITH_ACTUAL_SHA256_AFTER_PYPI_PUBLISH"

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.6,<2.0
  host:
    - python >=3.10
    - pip
    - maturin >=1.6,<2.0
    - htslib
  run:
    - python >=3.10
    - numpy >=1.21.0
    - pandas >=1.5.0,<3.0.0
    - polars >=0.19.0
    - scipy >=1.10.0
    - pysam >=0.21.0
    - pybedtools >=0.9.0
    - anndata >=0.8.0,<0.12.0
    - scanpy >=1.9.0
    - typer >=0.9.0
    - rich >=13.0.0
    - htslib

test:
  imports:
    - wasp2
    - wasp2_rust  # Verify Rust extension loads
    - counting
    - mapping
    - analysis
  commands:
    - wasp2-count --help
    - wasp2-map --help
    - wasp2-analyze --help

about:
  home: https://github.com/Jaureguy760/WASP2-final
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Allele-specific analysis of next-generation sequencing data with high-performance Rust backend
  description: |
    WASP2 is a high-performance toolkit for allele-specific analysis of NGS data.
    Features include mapping bias correction, allelic read counting, and
    multi-format variant support (VCF/BCF/PGEN). The Rust backend provides
    significant speedups over the original Python WASP implementation.
  doc_url: https://Jaureguy760.github.io/WASP2-final/
  dev_url: https://github.com/Jaureguy760/WASP2-final

extra:
  recipe-maintainers:
    - Jaureguy760
